// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////
#include "ui_SplashScreen.h"
#include "ui_MainScreen.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_background_png);   // assets/background.png
LV_IMG_DECLARE( ui_img_black_slider_png);   // assets/black_slider.png
LV_IMG_DECLARE( ui_img_red_slider_png);   // assets/red_slider.png

// FONTS
LV_FONT_DECLARE( ui_font_SairaCondensedBold20);
LV_FONT_DECLARE( ui_font_SairaSemiCondensedRegualar16);
LV_FONT_DECLARE( ui_font_SairaSemiCondensedExtraBold56);
LV_FONT_DECLARE( ui_font_SairaSemiCondensedExtraBold24);
LV_FONT_DECLARE( ui_font_SairaSemiCondensedExtraBold230);
LV_FONT_DECLARE( ui_font_SairaSemiCondensedExtraBold40);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
