// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_AnalogClusterScreen = NULL;
lv_obj_t * ui_Container11 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Container13 = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Slider1 = NULL;
lv_obj_t * ui_Bar4 = NULL;
lv_obj_t * ui_Image9 = NULL;
lv_obj_t * ui_Image10 = NULL;
lv_obj_t * ui_Image11 = NULL;
lv_obj_t * ui_Image12 = NULL;
lv_obj_t * ui_Container12 = NULL;
lv_obj_t * ui_Image23 = NULL;
lv_obj_t * ui_Container20 = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_Image24 = NULL;
lv_obj_t * ui_Container21 = NULL;
lv_obj_t * ui_Label26 = NULL;
lv_obj_t * ui_Label27 = NULL;
lv_obj_t * ui_Container14 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_Image13 = NULL;
lv_obj_t * ui_Container15 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_Image14 = NULL;
lv_obj_t * ui_Container22 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_Label28 = NULL;
lv_obj_t * ui_Container23 = NULL;
lv_obj_t * ui_Label29 = NULL;
lv_obj_t * ui_Image15 = NULL;
lv_obj_t * ui_Container24 = NULL;
lv_obj_t * ui_Label30 = NULL;
lv_obj_t * ui_Image16 = NULL;
lv_obj_t * ui_Container25 = NULL;
lv_obj_t * ui_Label31 = NULL;
lv_obj_t * ui_Label32 = NULL;
lv_obj_t * ui_Container26 = NULL;
lv_obj_t * ui_Label33 = NULL;
// event funtions
void ui_event_AnalogClusterScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_AllChannelsScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_AllChannelsScreen_screen_init);
    }
}

// build funtions

void ui_AnalogClusterScreen_screen_init(void)
{
    ui_AnalogClusterScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_AnalogClusterScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AnalogClusterScreen, lv_color_hex(0x141519), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AnalogClusterScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container11 = lv_obj_create(ui_AnalogClusterScreen);
    lv_obj_remove_style_all(ui_Container11);
    lv_obj_set_width(ui_Container11, 1024);
    lv_obj_set_height(ui_Container11, 50);
    lv_obj_set_x(ui_Container11, 0);
    lv_obj_set_y(ui_Container11, -270);
    lv_obj_set_align(ui_Container11, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container11, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container11, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_Container11);
    lv_img_set_src(ui_Image2, &ui_img_left_indicator_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container13 = lv_obj_create(ui_Container11);
    lv_obj_remove_style_all(ui_Container13);
    lv_obj_set_width(ui_Container13, 200);
    lv_obj_set_height(ui_Container13, 50);
    lv_obj_set_x(ui_Container13, -293);
    lv_obj_set_y(ui_Container13, -262);
    lv_obj_set_align(ui_Container13, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container13, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container13, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_img_create(ui_Container13);
    lv_img_set_src(ui_Image5, &ui_img_high_beam_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image7 = lv_img_create(ui_Container13);
    lv_img_set_src(ui_Image7, &ui_img_low_beam_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_img_create(ui_Container13);
    lv_img_set_src(ui_Image6, &ui_img_brake_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_img_create(ui_Container13);
    lv_img_set_src(ui_Image8, &ui_img_engine_earning_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_img_create(ui_Container11);
    lv_img_set_src(ui_Image4, &ui_img_right_indicator_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Slider1 = lv_slider_create(ui_AnalogClusterScreen);
    lv_slider_set_mode(ui_Slider1, LV_SLIDER_MODE_RANGE);
    lv_slider_set_value(ui_Slider1, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 50, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 832);
    lv_obj_set_height(ui_Slider1, 11);
    lv_obj_set_x(ui_Slider1, -5);
    lv_obj_set_y(ui_Slider1, -228);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Slider1, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Slider1, &ui_img_hor_bottom_slider_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Slider1, &ui_img_hor_top_slider_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Bar4 = lv_bar_create(ui_AnalogClusterScreen);
    lv_bar_set_value(ui_Bar4, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar4, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar4, 216);
    lv_obj_set_height(ui_Bar4, 32);
    lv_obj_set_x(ui_Bar4, 87);
    lv_obj_set_y(ui_Bar4, 13);
    lv_obj_set_align(ui_Bar4, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Bar4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Bar4, &ui_img_ver_bottom_slider_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_Bar4, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Bar4, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar4, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar4, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Bar4, &ui_img_ver_top_slider_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Image9 = lv_img_create(ui_AnalogClusterScreen);
    lv_img_set_src(ui_Image9, &ui_img_big_gauge_png);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image9, -281);
    lv_obj_set_y(ui_Image9, -58);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image10 = lv_img_create(ui_Image9);
    lv_img_set_src(ui_Image10, &ui_img_big_gauge_indicator_png);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Image10, 1250);

    ui_Image11 = lv_img_create(ui_AnalogClusterScreen);
    lv_img_set_src(ui_Image11, &ui_img_rpm_gauge_png);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image11, 267);
    lv_obj_set_y(ui_Image11, -66);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image12 = lv_img_create(ui_Image11);
    lv_img_set_src(ui_Image12, &ui_img_big_gauge_indicator_png);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container12 = lv_obj_create(ui_AnalogClusterScreen);
    lv_obj_remove_style_all(ui_Container12);
    lv_obj_set_width(ui_Container12, 1024);
    lv_obj_set_height(ui_Container12, 158);
    lv_obj_set_x(ui_Container12, 0);
    lv_obj_set_y(ui_Container12, 185);
    lv_obj_set_align(ui_Container12, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container12, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container12, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image23 = lv_img_create(ui_Container12);
    lv_img_set_src(ui_Image23, &ui_img_small_gauge_png);
    lv_obj_set_width(ui_Image23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image23, -284);
    lv_obj_set_y(ui_Image23, 179);
    lv_obj_set_align(ui_Image23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image23, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container20 = lv_obj_create(ui_Image23);
    lv_obj_remove_style_all(ui_Container20);
    lv_obj_set_width(ui_Container20, 100);
    lv_obj_set_height(ui_Container20, 14);
    lv_obj_set_x(ui_Container20, 0);
    lv_obj_set_y(ui_Container20, -42);
    lv_obj_set_align(ui_Container20, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container20, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container20, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container20, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label25 = lv_label_create(ui_Container20);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, -2);
    lv_obj_set_y(ui_Label25, 0);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "1/2");
    lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label25, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image24 = lv_img_create(ui_Image23);
    lv_img_set_src(ui_Image24, &ui_img_small_indicator_png);
    lv_obj_set_width(ui_Image24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image24, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image24, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container21 = lv_obj_create(ui_Image23);
    lv_obj_remove_style_all(ui_Container21);
    lv_obj_set_width(ui_Container21, 69);
    lv_obj_set_height(ui_Container21, 14);
    lv_obj_set_x(ui_Container21, -1);
    lv_obj_set_y(ui_Container21, 30);
    lv_obj_set_align(ui_Container21, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container21, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container21, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container21, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label26 = lv_label_create(ui_Container21);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, 264);
    lv_obj_set_y(ui_Label26, 204);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "E");
    lv_obj_set_style_text_color(ui_Label26, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label26, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label27 = lv_label_create(ui_Container21);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, 264);
    lv_obj_set_y(ui_Label27, 204);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "F");
    lv_obj_set_style_text_color(ui_Label27, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label27, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container14 = lv_obj_create(ui_Image23);
    lv_obj_remove_style_all(ui_Container14);
    lv_obj_set_width(ui_Container14, 100);
    lv_obj_set_height(ui_Container14, 14);
    lv_obj_set_x(ui_Container14, 1);
    lv_obj_set_y(ui_Container14, 43);
    lv_obj_set_align(ui_Container14, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container14, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container14, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label16 = lv_label_create(ui_Container14);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -2);
    lv_obj_set_y(ui_Label16, 0);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "FUEL");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image13 = lv_img_create(ui_Container12);
    lv_img_set_src(ui_Image13, &ui_img_small_gauge_png);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image13, -284);
    lv_obj_set_y(ui_Image13, 179);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container15 = lv_obj_create(ui_Image13);
    lv_obj_remove_style_all(ui_Container15);
    lv_obj_set_width(ui_Container15, 100);
    lv_obj_set_height(ui_Container15, 14);
    lv_obj_set_x(ui_Container15, 0);
    lv_obj_set_y(ui_Container15, -42);
    lv_obj_set_align(ui_Container15, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container15, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container15, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label17 = lv_label_create(ui_Container15);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -2);
    lv_obj_set_y(ui_Label17, 0);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "1/2");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image14 = lv_img_create(ui_Image13);
    lv_img_set_src(ui_Image14, &ui_img_small_indicator_png);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container22 = lv_obj_create(ui_Image13);
    lv_obj_remove_style_all(ui_Container22);
    lv_obj_set_width(ui_Container22, 69);
    lv_obj_set_height(ui_Container22, 14);
    lv_obj_set_x(ui_Container22, -1);
    lv_obj_set_y(ui_Container22, 30);
    lv_obj_set_align(ui_Container22, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container22, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container22, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container22, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label18 = lv_label_create(ui_Container22);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 264);
    lv_obj_set_y(ui_Label18, 204);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "E");
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label28 = lv_label_create(ui_Container22);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, 264);
    lv_obj_set_y(ui_Label28, 204);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "F");
    lv_obj_set_style_text_color(ui_Label28, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label28, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container23 = lv_obj_create(ui_Image13);
    lv_obj_remove_style_all(ui_Container23);
    lv_obj_set_width(ui_Container23, 100);
    lv_obj_set_height(ui_Container23, 14);
    lv_obj_set_x(ui_Container23, 1);
    lv_obj_set_y(ui_Container23, 43);
    lv_obj_set_align(ui_Container23, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container23, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container23, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container23, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label29 = lv_label_create(ui_Container23);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, -2);
    lv_obj_set_y(ui_Label29, 0);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "FUEL");
    lv_obj_set_style_text_color(ui_Label29, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label29, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image15 = lv_img_create(ui_Container12);
    lv_img_set_src(ui_Image15, &ui_img_small_gauge_png);
    lv_obj_set_width(ui_Image15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image15, -284);
    lv_obj_set_y(ui_Image15, 179);
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container24 = lv_obj_create(ui_Image15);
    lv_obj_remove_style_all(ui_Container24);
    lv_obj_set_width(ui_Container24, 100);
    lv_obj_set_height(ui_Container24, 14);
    lv_obj_set_x(ui_Container24, 0);
    lv_obj_set_y(ui_Container24, -42);
    lv_obj_set_align(ui_Container24, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container24, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container24, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container24, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label30 = lv_label_create(ui_Container24);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, -2);
    lv_obj_set_y(ui_Label30, 0);
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "1/2");
    lv_obj_set_style_text_color(ui_Label30, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label30, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image16 = lv_img_create(ui_Image15);
    lv_img_set_src(ui_Image16, &ui_img_small_indicator_png);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container25 = lv_obj_create(ui_Image15);
    lv_obj_remove_style_all(ui_Container25);
    lv_obj_set_width(ui_Container25, 69);
    lv_obj_set_height(ui_Container25, 14);
    lv_obj_set_x(ui_Container25, -1);
    lv_obj_set_y(ui_Container25, 30);
    lv_obj_set_align(ui_Container25, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container25, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container25, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container25, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label31 = lv_label_create(ui_Container25);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label31, 264);
    lv_obj_set_y(ui_Label31, 204);
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "E");
    lv_obj_set_style_text_color(ui_Label31, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label31, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_Container25);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label32, 264);
    lv_obj_set_y(ui_Label32, 204);
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "F");
    lv_obj_set_style_text_color(ui_Label32, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label32, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container26 = lv_obj_create(ui_Image15);
    lv_obj_remove_style_all(ui_Container26);
    lv_obj_set_width(ui_Container26, 100);
    lv_obj_set_height(ui_Container26, 14);
    lv_obj_set_x(ui_Container26, 1);
    lv_obj_set_y(ui_Container26, 43);
    lv_obj_set_align(ui_Container26, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container26, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container26, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container26, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label33 = lv_label_create(ui_Container26);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label33, -2);
    lv_obj_set_y(ui_Label33, 0);
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "FUEL");
    lv_obj_set_style_text_color(ui_Label33, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label33, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_AnalogClusterScreen, ui_event_AnalogClusterScreen, LV_EVENT_ALL, NULL);

}

void ui_AnalogClusterScreen_screen_destroy(void)
{
    if(ui_AnalogClusterScreen) lv_obj_del(ui_AnalogClusterScreen);

    // NULL screen variables
    ui_AnalogClusterScreen = NULL;
    ui_Container11 = NULL;
    ui_Image2 = NULL;
    ui_Container13 = NULL;
    ui_Image5 = NULL;
    ui_Image7 = NULL;
    ui_Image6 = NULL;
    ui_Image8 = NULL;
    ui_Image4 = NULL;
    ui_Slider1 = NULL;
    ui_Bar4 = NULL;
    ui_Image9 = NULL;
    ui_Image10 = NULL;
    ui_Image11 = NULL;
    ui_Image12 = NULL;
    ui_Container12 = NULL;
    ui_Image23 = NULL;
    ui_Container20 = NULL;
    ui_Label25 = NULL;
    ui_Image24 = NULL;
    ui_Container21 = NULL;
    ui_Label26 = NULL;
    ui_Label27 = NULL;
    ui_Container14 = NULL;
    ui_Label16 = NULL;
    ui_Image13 = NULL;
    ui_Container15 = NULL;
    ui_Label17 = NULL;
    ui_Image14 = NULL;
    ui_Container22 = NULL;
    ui_Label18 = NULL;
    ui_Label28 = NULL;
    ui_Container23 = NULL;
    ui_Label29 = NULL;
    ui_Image15 = NULL;
    ui_Container24 = NULL;
    ui_Label30 = NULL;
    ui_Image16 = NULL;
    ui_Container25 = NULL;
    ui_Label31 = NULL;
    ui_Label32 = NULL;
    ui_Container26 = NULL;
    ui_Label33 = NULL;

}
