// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_AnalogClusterScreen = NULL;lv_obj_t *ui_Container11 = NULL;lv_obj_t *ui_Image2 = NULL;lv_obj_t *ui_Container13 = NULL;lv_obj_t *ui_Image5 = NULL;lv_obj_t *ui_Image7 = NULL;lv_obj_t *ui_Image6 = NULL;lv_obj_t *ui_Image8 = NULL;lv_obj_t *ui_Image4 = NULL;lv_obj_t *ui_Slider1 = NULL;lv_obj_t *ui_Bar4 = NULL;lv_obj_t *ui_Container14 = NULL;lv_obj_t *ui_Image9 = NULL;lv_obj_t *ui_Image10 = NULL;lv_obj_t *ui_Image11 = NULL;lv_obj_t *ui_Image12 = NULL;lv_obj_t *ui_Container12 = NULL;lv_obj_t *ui_Image13 = NULL;lv_obj_t *ui_Image14 = NULL;lv_obj_t *ui_Image15 = NULL;lv_obj_t *ui_Image16 = NULL;lv_obj_t *ui_Image17 = NULL;lv_obj_t *ui_Image18 = NULL;
// event funtions

// build funtions

void ui_AnalogClusterScreen_screen_init(void)
{
ui_AnalogClusterScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_AnalogClusterScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_AnalogClusterScreen, lv_color_hex(0x141519), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AnalogClusterScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container11 = lv_obj_create(ui_AnalogClusterScreen);
lv_obj_remove_style_all(ui_Container11);
lv_obj_set_width( ui_Container11, 1024);
lv_obj_set_height( ui_Container11, 50);
lv_obj_set_x( ui_Container11, 0 );
lv_obj_set_y( ui_Container11, -270 );
lv_obj_set_align( ui_Container11, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container11,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container11, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image2 = lv_img_create(ui_Container11);
lv_img_set_src(ui_Image2, &ui_img_left_indicator_png);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container13 = lv_obj_create(ui_Container11);
lv_obj_remove_style_all(ui_Container13);
lv_obj_set_width( ui_Container13, 200);
lv_obj_set_height( ui_Container13, 50);
lv_obj_set_x( ui_Container13, -293 );
lv_obj_set_y( ui_Container13, -262 );
lv_obj_set_align( ui_Container13, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container13,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container13, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image5 = lv_img_create(ui_Container13);
lv_img_set_src(ui_Image5, &ui_img_high_beam_png);
lv_obj_set_width( ui_Image5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image7 = lv_img_create(ui_Container13);
lv_img_set_src(ui_Image7, &ui_img_low_beam_png);
lv_obj_set_width( ui_Image7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image7, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image6 = lv_img_create(ui_Container13);
lv_img_set_src(ui_Image6, &ui_img_brake_png);
lv_obj_set_width( ui_Image6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image6, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image8 = lv_img_create(ui_Container13);
lv_img_set_src(ui_Image8, &ui_img_engine_earning_png);
lv_obj_set_width( ui_Image8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image8, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image8, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image4 = lv_img_create(ui_Container11);
lv_img_set_src(ui_Image4, &ui_img_right_indicator_png);
lv_obj_set_width( ui_Image4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Slider1 = lv_slider_create(ui_AnalogClusterScreen);
lv_slider_set_mode(ui_Slider1, LV_SLIDER_MODE_RANGE);
lv_slider_set_value( ui_Slider1, 50, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_Slider1)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_Slider1, 50, LV_ANIM_OFF);
lv_obj_set_width( ui_Slider1, 832);
lv_obj_set_height( ui_Slider1, 11);
lv_obj_set_x( ui_Slider1, -5 );
lv_obj_set_y( ui_Slider1, -228 );
lv_obj_set_align( ui_Slider1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Slider1, LV_OBJ_FLAG_CLICK_FOCUSABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Slider1, &ui_img_hor_bottom_slider_png, LV_PART_MAIN | LV_STATE_DEFAULT );

lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider1, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Slider1, &ui_img_hor_top_slider_png, LV_PART_INDICATOR | LV_STATE_DEFAULT );

lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider1, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Bar4 = lv_bar_create(ui_AnalogClusterScreen);
lv_bar_set_value(ui_Bar4,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_Bar4, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Bar4, 216);
lv_obj_set_height( ui_Bar4, 32);
lv_obj_set_x( ui_Bar4, 87 );
lv_obj_set_y( ui_Bar4, 13 );
lv_obj_set_align( ui_Bar4, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Bar4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Bar4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Bar4, &ui_img_ver_bottom_slider_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_transform_angle(ui_Bar4, -900, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Bar4, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Bar4, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar4, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Bar4, &ui_img_ver_top_slider_png, LV_PART_INDICATOR | LV_STATE_DEFAULT );

ui_Container14 = lv_obj_create(ui_AnalogClusterScreen);
lv_obj_remove_style_all(ui_Container14);
lv_obj_set_width( ui_Container14, 100);
lv_obj_set_height( ui_Container14, 50);
lv_obj_set_align( ui_Container14, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image9 = lv_img_create(ui_AnalogClusterScreen);
lv_img_set_src(ui_Image9, &ui_img_big_gauge_png);
lv_obj_set_width( ui_Image9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image9, -281 );
lv_obj_set_y( ui_Image9, -58 );
lv_obj_set_align( ui_Image9, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image9, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image10 = lv_img_create(ui_Image9);
lv_img_set_src(ui_Image10, &ui_img_big_gauge_indicator_png);
lv_obj_set_width( ui_Image10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image10, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image10, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_Image10,1250);

ui_Image11 = lv_img_create(ui_AnalogClusterScreen);
lv_img_set_src(ui_Image11, &ui_img_rpm_gauge_png);
lv_obj_set_width( ui_Image11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image11, 267 );
lv_obj_set_y( ui_Image11, -66 );
lv_obj_set_align( ui_Image11, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image11, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image11, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image12 = lv_img_create(ui_Image11);
lv_img_set_src(ui_Image12, &ui_img_big_gauge_indicator_png);
lv_obj_set_width( ui_Image12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image12, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image12, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image12, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container12 = lv_obj_create(ui_AnalogClusterScreen);
lv_obj_remove_style_all(ui_Container12);
lv_obj_set_width( ui_Container12, 1024);
lv_obj_set_height( ui_Container12, 158);
lv_obj_set_x( ui_Container12, 0 );
lv_obj_set_y( ui_Container12, 185 );
lv_obj_set_align( ui_Container12, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container12,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container12, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image13 = lv_img_create(ui_Container12);
lv_img_set_src(ui_Image13, &ui_img_small_gauge_png);
lv_obj_set_width( ui_Image13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image13, -284 );
lv_obj_set_y( ui_Image13, 179 );
lv_obj_set_align( ui_Image13, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image13, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image13, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image14 = lv_img_create(ui_Image13);
lv_img_set_src(ui_Image14, &ui_img_small_indicator_png);
lv_obj_set_width( ui_Image14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image14, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image14, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image14, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image15 = lv_img_create(ui_Container12);
lv_img_set_src(ui_Image15, &ui_img_small_gauge_png);
lv_obj_set_width( ui_Image15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image15, -284 );
lv_obj_set_y( ui_Image15, 179 );
lv_obj_set_align( ui_Image15, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image15, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image15, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image16 = lv_img_create(ui_Image15);
lv_img_set_src(ui_Image16, &ui_img_small_indicator_png);
lv_obj_set_width( ui_Image16, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image16, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image16, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image16, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image16, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image17 = lv_img_create(ui_Container12);
lv_img_set_src(ui_Image17, &ui_img_small_gauge_png);
lv_obj_set_width( ui_Image17, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image17, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image17, -284 );
lv_obj_set_y( ui_Image17, 179 );
lv_obj_set_align( ui_Image17, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image17, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image17, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image18 = lv_img_create(ui_Image17);
lv_img_set_src(ui_Image18, &ui_img_small_indicator_png);
lv_obj_set_width( ui_Image18, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image18, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image18, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image18, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image18, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}

void ui_AnalogClusterScreen_screen_destroy(void)
{
   if (ui_AnalogClusterScreen) lv_obj_del(ui_AnalogClusterScreen);

// NULL screen variables
ui_AnalogClusterScreen= NULL;
ui_Container11= NULL;
ui_Image2= NULL;
ui_Container13= NULL;
ui_Image5= NULL;
ui_Image7= NULL;
ui_Image6= NULL;
ui_Image8= NULL;
ui_Image4= NULL;
ui_Slider1= NULL;
ui_Bar4= NULL;
ui_Container14= NULL;
ui_Image9= NULL;
ui_Image10= NULL;
ui_Image11= NULL;
ui_Image12= NULL;
ui_Container12= NULL;
ui_Image13= NULL;
ui_Image14= NULL;
ui_Image15= NULL;
ui_Image16= NULL;
ui_Image17= NULL;
ui_Image18= NULL;

}
