// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_AnalogClusterScreen = NULL;
lv_obj_t * ui_Container11 = NULL;
lv_obj_t * ui_LeftIndicator = NULL;
lv_obj_t * ui_Container13 = NULL;
lv_obj_t * ui_HighBeam = NULL;
lv_obj_t * ui_LowBeam = NULL;
lv_obj_t * ui_Brake = NULL;
lv_obj_t * ui_Warning = NULL;
lv_obj_t * ui_RightIndicator = NULL;
lv_obj_t * ui_AnalogRPMSliderHorizontal = NULL;
lv_obj_t * ui_AnalogRPMSlider = NULL;
lv_obj_t * ui_SpeedAnalogGauge = NULL;
lv_obj_t * ui_SpeedGaugeIndicator = NULL;
lv_obj_t * ui_RPMGauge = NULL;
lv_obj_t * ui_RPMIndicator = NULL;
lv_obj_t * ui_Container12 = NULL;
lv_obj_t * ui_AnalogGauge1 = NULL;
lv_obj_t * ui_Container20 = NULL;
lv_obj_t * ui_MidLevel = NULL;
lv_obj_t * ui_Image24 = NULL;
lv_obj_t * ui_Container21 = NULL;
lv_obj_t * ui_LowLevel1 = NULL;
lv_obj_t * ui_HighLevel1 = NULL;
lv_obj_t * ui_Container14 = NULL;
lv_obj_t * ui_AnalogGaugeName1 = NULL;
lv_obj_t * ui_AnalogGauge2 = NULL;
lv_obj_t * ui_Container15 = NULL;
lv_obj_t * ui_MidLevel1 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Container22 = NULL;
lv_obj_t * ui_LowLevel2 = NULL;
lv_obj_t * ui_HighLevel2 = NULL;
lv_obj_t * ui_Container23 = NULL;
lv_obj_t * ui_AnalogGaugeName2 = NULL;
lv_obj_t * ui_AnalogGauge3 = NULL;
lv_obj_t * ui_Container24 = NULL;
lv_obj_t * ui_MidLevel2 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Container25 = NULL;
lv_obj_t * ui_LowLevel3 = NULL;
lv_obj_t * ui_HighLevel3 = NULL;
lv_obj_t * ui_Container26 = NULL;
lv_obj_t * ui_AnalogGaugeName3 = NULL;
// event funtions

// build funtions

void ui_AnalogClusterScreen_screen_init(void)
{
    ui_AnalogClusterScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_AnalogClusterScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AnalogClusterScreen, lv_color_hex(0x141519), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AnalogClusterScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container11 = lv_obj_create(ui_AnalogClusterScreen);
    lv_obj_remove_style_all(ui_Container11);
    lv_obj_set_width(ui_Container11, 1024);
    lv_obj_set_height(ui_Container11, 50);
    lv_obj_set_x(ui_Container11, 0);
    lv_obj_set_y(ui_Container11, -270);
    lv_obj_set_align(ui_Container11, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container11, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container11, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LeftIndicator = lv_img_create(ui_Container11);
    lv_img_set_src(ui_LeftIndicator, &ui_img_left_indicator_png);
    lv_obj_set_width(ui_LeftIndicator, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LeftIndicator, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LeftIndicator, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LeftIndicator, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LeftIndicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container13 = lv_obj_create(ui_Container11);
    lv_obj_remove_style_all(ui_Container13);
    lv_obj_set_width(ui_Container13, 200);
    lv_obj_set_height(ui_Container13, 50);
    lv_obj_set_x(ui_Container13, -293);
    lv_obj_set_y(ui_Container13, -262);
    lv_obj_set_align(ui_Container13, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container13, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container13, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HighBeam = lv_img_create(ui_Container13);
    lv_img_set_src(ui_HighBeam, &ui_img_high_beam_png);
    lv_obj_set_width(ui_HighBeam, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HighBeam, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HighBeam, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HighBeam, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HighBeam, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LowBeam = lv_img_create(ui_Container13);
    lv_img_set_src(ui_LowBeam, &ui_img_low_beam_png);
    lv_obj_set_width(ui_LowBeam, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LowBeam, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LowBeam, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LowBeam, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LowBeam, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Brake = lv_img_create(ui_Container13);
    lv_img_set_src(ui_Brake, &ui_img_brake_png);
    lv_obj_set_width(ui_Brake, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Brake, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Brake, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Brake, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Brake, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Warning = lv_img_create(ui_Container13);
    lv_img_set_src(ui_Warning, &ui_img_engine_earning_png);
    lv_obj_set_width(ui_Warning, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Warning, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Warning, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Warning, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Warning, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RightIndicator = lv_img_create(ui_Container11);
    lv_img_set_src(ui_RightIndicator, &ui_img_right_indicator_png);
    lv_obj_set_width(ui_RightIndicator, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RightIndicator, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RightIndicator, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RightIndicator, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_RightIndicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AnalogRPMSliderHorizontal = lv_slider_create(ui_AnalogClusterScreen);
    lv_slider_set_mode(ui_AnalogRPMSliderHorizontal, LV_SLIDER_MODE_RANGE);
    lv_slider_set_value(ui_AnalogRPMSliderHorizontal, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_AnalogRPMSliderHorizontal) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_AnalogRPMSliderHorizontal, 50, LV_ANIM_OFF);
    lv_obj_set_width(ui_AnalogRPMSliderHorizontal, 832);
    lv_obj_set_height(ui_AnalogRPMSliderHorizontal, 11);
    lv_obj_set_x(ui_AnalogRPMSliderHorizontal, -5);
    lv_obj_set_y(ui_AnalogRPMSliderHorizontal, -228);
    lv_obj_set_align(ui_AnalogRPMSliderHorizontal, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AnalogRPMSliderHorizontal, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AnalogRPMSliderHorizontal, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AnalogRPMSliderHorizontal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_AnalogRPMSliderHorizontal, &ui_img_hor_bottom_slider_png,
                                LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_AnalogRPMSliderHorizontal, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AnalogRPMSliderHorizontal, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_AnalogRPMSliderHorizontal, &ui_img_hor_top_slider_png,
                                LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_AnalogRPMSliderHorizontal, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AnalogRPMSliderHorizontal, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_AnalogRPMSlider = lv_bar_create(ui_AnalogClusterScreen);
    lv_bar_set_value(ui_AnalogRPMSlider, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_AnalogRPMSlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_AnalogRPMSlider, 216);
    lv_obj_set_height(ui_AnalogRPMSlider, 32);
    lv_obj_set_x(ui_AnalogRPMSlider, 87);
    lv_obj_set_y(ui_AnalogRPMSlider, 13);
    lv_obj_set_align(ui_AnalogRPMSlider, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_AnalogRPMSlider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AnalogRPMSlider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AnalogRPMSlider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_AnalogRPMSlider, &ui_img_ver_bottom_slider_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_AnalogRPMSlider, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_AnalogRPMSlider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AnalogRPMSlider, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AnalogRPMSlider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_AnalogRPMSlider, &ui_img_ver_top_slider_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_SpeedAnalogGauge = lv_img_create(ui_AnalogClusterScreen);
    lv_img_set_src(ui_SpeedAnalogGauge, &ui_img_big_gauge_png);
    lv_obj_set_width(ui_SpeedAnalogGauge, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedAnalogGauge, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedAnalogGauge, -281);
    lv_obj_set_y(ui_SpeedAnalogGauge, -58);
    lv_obj_set_align(ui_SpeedAnalogGauge, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SpeedAnalogGauge, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SpeedAnalogGauge, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SpeedGaugeIndicator = lv_img_create(ui_SpeedAnalogGauge);
    lv_img_set_src(ui_SpeedGaugeIndicator, &ui_img_big_gauge_indicator_png);
    lv_obj_set_width(ui_SpeedGaugeIndicator, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedGaugeIndicator, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SpeedGaugeIndicator, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SpeedGaugeIndicator, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SpeedGaugeIndicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_SpeedGaugeIndicator, 1250);

    ui_RPMGauge = lv_img_create(ui_AnalogClusterScreen);
    lv_img_set_src(ui_RPMGauge, &ui_img_rpm_gauge_png);
    lv_obj_set_width(ui_RPMGauge, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RPMGauge, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RPMGauge, 267);
    lv_obj_set_y(ui_RPMGauge, -66);
    lv_obj_set_align(ui_RPMGauge, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RPMGauge, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_RPMGauge, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RPMIndicator = lv_img_create(ui_RPMGauge);
    lv_img_set_src(ui_RPMIndicator, &ui_img_big_gauge_indicator_png);
    lv_obj_set_width(ui_RPMIndicator, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RPMIndicator, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RPMIndicator, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RPMIndicator, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_RPMIndicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container12 = lv_obj_create(ui_AnalogClusterScreen);
    lv_obj_remove_style_all(ui_Container12);
    lv_obj_set_width(ui_Container12, 1024);
    lv_obj_set_height(ui_Container12, 158);
    lv_obj_set_x(ui_Container12, 0);
    lv_obj_set_y(ui_Container12, 185);
    lv_obj_set_align(ui_Container12, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container12, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container12, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AnalogGauge1 = lv_img_create(ui_Container12);
    lv_img_set_src(ui_AnalogGauge1, &ui_img_small_gauge_png);
    lv_obj_set_width(ui_AnalogGauge1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AnalogGauge1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AnalogGauge1, -284);
    lv_obj_set_y(ui_AnalogGauge1, 179);
    lv_obj_set_align(ui_AnalogGauge1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AnalogGauge1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AnalogGauge1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container20 = lv_obj_create(ui_AnalogGauge1);
    lv_obj_remove_style_all(ui_Container20);
    lv_obj_set_width(ui_Container20, 100);
    lv_obj_set_height(ui_Container20, 14);
    lv_obj_set_x(ui_Container20, 0);
    lv_obj_set_y(ui_Container20, -42);
    lv_obj_set_align(ui_Container20, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container20, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container20, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container20, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MidLevel = lv_label_create(ui_Container20);
    lv_obj_set_width(ui_MidLevel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MidLevel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MidLevel, -2);
    lv_obj_set_y(ui_MidLevel, 0);
    lv_obj_set_align(ui_MidLevel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MidLevel, "1/2");
    lv_obj_set_style_text_color(ui_MidLevel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MidLevel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MidLevel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image24 = lv_img_create(ui_AnalogGauge1);
    lv_img_set_src(ui_Image24, &ui_img_small_indicator_png);
    lv_obj_set_width(ui_Image24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image24, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image24, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container21 = lv_obj_create(ui_AnalogGauge1);
    lv_obj_remove_style_all(ui_Container21);
    lv_obj_set_width(ui_Container21, 69);
    lv_obj_set_height(ui_Container21, 14);
    lv_obj_set_x(ui_Container21, -1);
    lv_obj_set_y(ui_Container21, 30);
    lv_obj_set_align(ui_Container21, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container21, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container21, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container21, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LowLevel1 = lv_label_create(ui_Container21);
    lv_obj_set_width(ui_LowLevel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LowLevel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LowLevel1, 264);
    lv_obj_set_y(ui_LowLevel1, 204);
    lv_obj_set_align(ui_LowLevel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LowLevel1, "E");
    lv_obj_set_style_text_color(ui_LowLevel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LowLevel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LowLevel1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HighLevel1 = lv_label_create(ui_Container21);
    lv_obj_set_width(ui_HighLevel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HighLevel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HighLevel1, 264);
    lv_obj_set_y(ui_HighLevel1, 204);
    lv_obj_set_align(ui_HighLevel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HighLevel1, "F");
    lv_obj_set_style_text_color(ui_HighLevel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HighLevel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HighLevel1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container14 = lv_obj_create(ui_AnalogGauge1);
    lv_obj_remove_style_all(ui_Container14);
    lv_obj_set_width(ui_Container14, 100);
    lv_obj_set_height(ui_Container14, 14);
    lv_obj_set_x(ui_Container14, 1);
    lv_obj_set_y(ui_Container14, 43);
    lv_obj_set_align(ui_Container14, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container14, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container14, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AnalogGaugeName1 = lv_label_create(ui_Container14);
    lv_obj_set_width(ui_AnalogGaugeName1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AnalogGaugeName1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AnalogGaugeName1, -2);
    lv_obj_set_y(ui_AnalogGaugeName1, 0);
    lv_obj_set_align(ui_AnalogGaugeName1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AnalogGaugeName1, "FUEL");
    lv_obj_set_style_text_color(ui_AnalogGaugeName1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AnalogGaugeName1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AnalogGaugeName1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AnalogGauge2 = lv_img_create(ui_Container12);
    lv_img_set_src(ui_AnalogGauge2, &ui_img_small_gauge_png);
    lv_obj_set_width(ui_AnalogGauge2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AnalogGauge2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AnalogGauge2, -284);
    lv_obj_set_y(ui_AnalogGauge2, 179);
    lv_obj_set_align(ui_AnalogGauge2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AnalogGauge2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AnalogGauge2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container15 = lv_obj_create(ui_AnalogGauge2);
    lv_obj_remove_style_all(ui_Container15);
    lv_obj_set_width(ui_Container15, 100);
    lv_obj_set_height(ui_Container15, 14);
    lv_obj_set_x(ui_Container15, 0);
    lv_obj_set_y(ui_Container15, -42);
    lv_obj_set_align(ui_Container15, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container15, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container15, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MidLevel1 = lv_label_create(ui_Container15);
    lv_obj_set_width(ui_MidLevel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MidLevel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MidLevel1, -2);
    lv_obj_set_y(ui_MidLevel1, 0);
    lv_obj_set_align(ui_MidLevel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MidLevel1, "1/2");
    lv_obj_set_style_text_color(ui_MidLevel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MidLevel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MidLevel1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_AnalogGauge2);
    lv_img_set_src(ui_Image2, &ui_img_small_indicator_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container22 = lv_obj_create(ui_AnalogGauge2);
    lv_obj_remove_style_all(ui_Container22);
    lv_obj_set_width(ui_Container22, 69);
    lv_obj_set_height(ui_Container22, 14);
    lv_obj_set_x(ui_Container22, -1);
    lv_obj_set_y(ui_Container22, 30);
    lv_obj_set_align(ui_Container22, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container22, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container22, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container22, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LowLevel2 = lv_label_create(ui_Container22);
    lv_obj_set_width(ui_LowLevel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LowLevel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LowLevel2, 264);
    lv_obj_set_y(ui_LowLevel2, 204);
    lv_obj_set_align(ui_LowLevel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LowLevel2, "E");
    lv_obj_set_style_text_color(ui_LowLevel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LowLevel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LowLevel2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HighLevel2 = lv_label_create(ui_Container22);
    lv_obj_set_width(ui_HighLevel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HighLevel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HighLevel2, 264);
    lv_obj_set_y(ui_HighLevel2, 204);
    lv_obj_set_align(ui_HighLevel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HighLevel2, "F");
    lv_obj_set_style_text_color(ui_HighLevel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HighLevel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HighLevel2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container23 = lv_obj_create(ui_AnalogGauge2);
    lv_obj_remove_style_all(ui_Container23);
    lv_obj_set_width(ui_Container23, 100);
    lv_obj_set_height(ui_Container23, 14);
    lv_obj_set_x(ui_Container23, 1);
    lv_obj_set_y(ui_Container23, 43);
    lv_obj_set_align(ui_Container23, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container23, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container23, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container23, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AnalogGaugeName2 = lv_label_create(ui_Container23);
    lv_obj_set_width(ui_AnalogGaugeName2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AnalogGaugeName2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AnalogGaugeName2, -2);
    lv_obj_set_y(ui_AnalogGaugeName2, 0);
    lv_obj_set_align(ui_AnalogGaugeName2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AnalogGaugeName2, "FUEL");
    lv_obj_set_style_text_color(ui_AnalogGaugeName2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AnalogGaugeName2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AnalogGaugeName2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AnalogGauge3 = lv_img_create(ui_Container12);
    lv_img_set_src(ui_AnalogGauge3, &ui_img_small_gauge_png);
    lv_obj_set_width(ui_AnalogGauge3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AnalogGauge3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AnalogGauge3, -284);
    lv_obj_set_y(ui_AnalogGauge3, 179);
    lv_obj_set_align(ui_AnalogGauge3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AnalogGauge3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AnalogGauge3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container24 = lv_obj_create(ui_AnalogGauge3);
    lv_obj_remove_style_all(ui_Container24);
    lv_obj_set_width(ui_Container24, 100);
    lv_obj_set_height(ui_Container24, 14);
    lv_obj_set_x(ui_Container24, 0);
    lv_obj_set_y(ui_Container24, -42);
    lv_obj_set_align(ui_Container24, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container24, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container24, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container24, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MidLevel2 = lv_label_create(ui_Container24);
    lv_obj_set_width(ui_MidLevel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MidLevel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MidLevel2, -2);
    lv_obj_set_y(ui_MidLevel2, 0);
    lv_obj_set_align(ui_MidLevel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MidLevel2, "1/2");
    lv_obj_set_style_text_color(ui_MidLevel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MidLevel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MidLevel2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_AnalogGauge3);
    lv_img_set_src(ui_Image4, &ui_img_small_indicator_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container25 = lv_obj_create(ui_AnalogGauge3);
    lv_obj_remove_style_all(ui_Container25);
    lv_obj_set_width(ui_Container25, 69);
    lv_obj_set_height(ui_Container25, 14);
    lv_obj_set_x(ui_Container25, -1);
    lv_obj_set_y(ui_Container25, 30);
    lv_obj_set_align(ui_Container25, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container25, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container25, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container25, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LowLevel3 = lv_label_create(ui_Container25);
    lv_obj_set_width(ui_LowLevel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LowLevel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LowLevel3, 264);
    lv_obj_set_y(ui_LowLevel3, 204);
    lv_obj_set_align(ui_LowLevel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LowLevel3, "E");
    lv_obj_set_style_text_color(ui_LowLevel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LowLevel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LowLevel3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HighLevel3 = lv_label_create(ui_Container25);
    lv_obj_set_width(ui_HighLevel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HighLevel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HighLevel3, 264);
    lv_obj_set_y(ui_HighLevel3, 204);
    lv_obj_set_align(ui_HighLevel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HighLevel3, "F");
    lv_obj_set_style_text_color(ui_HighLevel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HighLevel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HighLevel3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container26 = lv_obj_create(ui_AnalogGauge3);
    lv_obj_remove_style_all(ui_Container26);
    lv_obj_set_width(ui_Container26, 100);
    lv_obj_set_height(ui_Container26, 14);
    lv_obj_set_x(ui_Container26, 1);
    lv_obj_set_y(ui_Container26, 43);
    lv_obj_set_align(ui_Container26, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container26, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container26, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container26, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AnalogGaugeName3 = lv_label_create(ui_Container26);
    lv_obj_set_width(ui_AnalogGaugeName3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AnalogGaugeName3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AnalogGaugeName3, -2);
    lv_obj_set_y(ui_AnalogGaugeName3, 0);
    lv_obj_set_align(ui_AnalogGaugeName3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AnalogGaugeName3, "FUEL");
    lv_obj_set_style_text_color(ui_AnalogGaugeName3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AnalogGaugeName3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AnalogGaugeName3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_AnalogClusterScreen_screen_destroy(void)
{
    if(ui_AnalogClusterScreen) lv_obj_del(ui_AnalogClusterScreen);

    // NULL screen variables
    ui_AnalogClusterScreen = NULL;
    ui_Container11 = NULL;
    ui_LeftIndicator = NULL;
    ui_Container13 = NULL;
    ui_HighBeam = NULL;
    ui_LowBeam = NULL;
    ui_Brake = NULL;
    ui_Warning = NULL;
    ui_RightIndicator = NULL;
    ui_AnalogRPMSliderHorizontal = NULL;
    ui_AnalogRPMSlider = NULL;
    ui_SpeedAnalogGauge = NULL;
    ui_SpeedGaugeIndicator = NULL;
    ui_RPMGauge = NULL;
    ui_RPMIndicator = NULL;
    ui_Container12 = NULL;
    ui_AnalogGauge1 = NULL;
    ui_Container20 = NULL;
    ui_MidLevel = NULL;
    ui_Image24 = NULL;
    ui_Container21 = NULL;
    ui_LowLevel1 = NULL;
    ui_HighLevel1 = NULL;
    ui_Container14 = NULL;
    ui_AnalogGaugeName1 = NULL;
    ui_AnalogGauge2 = NULL;
    ui_Container15 = NULL;
    ui_MidLevel1 = NULL;
    ui_Image2 = NULL;
    ui_Container22 = NULL;
    ui_LowLevel2 = NULL;
    ui_HighLevel2 = NULL;
    ui_Container23 = NULL;
    ui_AnalogGaugeName2 = NULL;
    ui_AnalogGauge3 = NULL;
    ui_Container24 = NULL;
    ui_MidLevel2 = NULL;
    ui_Image4 = NULL;
    ui_Container25 = NULL;
    ui_LowLevel3 = NULL;
    ui_HighLevel3 = NULL;
    ui_Container26 = NULL;
    ui_AnalogGaugeName3 = NULL;

}
