// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_ANALOGCLUSTERSCREEN_H
#define UI_ANALOGCLUSTERSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif


// SCREEN: ui_AnalogClusterScreen
extern void ui_AnalogClusterScreen_screen_init(void);
extern void ui_AnalogClusterScreen_screen_destroy(void);
extern lv_obj_t *ui_AnalogClusterScreen;
extern lv_obj_t *ui_Container11;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_Container13;
extern lv_obj_t *ui_Image5;
extern lv_obj_t *ui_Image7;
extern lv_obj_t *ui_Image6;
extern lv_obj_t *ui_Image8;
extern lv_obj_t *ui_Image4;
extern lv_obj_t *ui_Slider1;
extern lv_obj_t *ui_Bar4;
extern lv_obj_t *ui_Container14;
extern lv_obj_t *ui_Image9;
extern lv_obj_t *ui_Image10;
extern lv_obj_t *ui_Image11;
extern lv_obj_t *ui_Image12;
extern lv_obj_t *ui_Container12;
extern lv_obj_t *ui_Image13;
extern lv_obj_t *ui_Image14;
extern lv_obj_t *ui_Image15;
extern lv_obj_t *ui_Image16;
extern lv_obj_t *ui_Image17;
extern lv_obj_t *ui_Image18;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

