// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_ALLCHANNELSSCREEN_H
#define UI_ALLCHANNELSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_AllChannelsScreen
extern void ui_AllChannelsScreen_screen_init(void);
extern void ui_AllChannelsScreen_screen_destroy(void);
extern lv_obj_t * ui_AllChannelsScreen;
extern lv_obj_t * ui_Container72;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Container18;
extern lv_obj_t * ui_BackContainer1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Container16;
extern lv_obj_t * ui_AuxChannelLabel1;
extern lv_obj_t * ui_Container17;
extern lv_obj_t * ui_AuxChannelValue1;
extern lv_obj_t * ui_AuxChannelSymbol1;
extern lv_obj_t * ui_AuxChannelBar1;
extern lv_obj_t * ui_BackContainer2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Container19;
extern lv_obj_t * ui_AuxChannelLabel2;
extern lv_obj_t * ui_Container27;
extern lv_obj_t * ui_AuxChannelValue2;
extern lv_obj_t * ui_AuxChannelSymbol2;
extern lv_obj_t * ui_AuxChannelBar2;
extern lv_obj_t * ui_BackContainer3;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Container28;
extern lv_obj_t * ui_AuxChannelLabel3;
extern lv_obj_t * ui_Container29;
extern lv_obj_t * ui_AuxChannelValue3;
extern lv_obj_t * ui_AuxChannelSymbol3;
extern lv_obj_t * ui_AuxChannelBar3;
extern lv_obj_t * ui_BackContainer4;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Container30;
extern lv_obj_t * ui_AuxChannelLabel4;
extern lv_obj_t * ui_Container31;
extern lv_obj_t * ui_AuxChannelValue4;
extern lv_obj_t * ui_AuxChannelSymbol4;
extern lv_obj_t * ui_AuxChannelBar4;
extern lv_obj_t * ui_BackContainer5;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Container32;
extern lv_obj_t * ui_AuxChannelLabel5;
extern lv_obj_t * ui_Container33;
extern lv_obj_t * ui_AuxChannelValue5;
extern lv_obj_t * ui_AuxChannelSymbol5;
extern lv_obj_t * ui_AuxChannelBar5;
extern lv_obj_t * ui_BackContainer6;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Container34;
extern lv_obj_t * ui_AuxChannelLabel6;
extern lv_obj_t * ui_Container35;
extern lv_obj_t * ui_AuxChannelValue6;
extern lv_obj_t * ui_AuxChannelSymbol6;
extern lv_obj_t * ui_AuxChannelBar6;
extern lv_obj_t * ui_BackContainer7;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Container36;
extern lv_obj_t * ui_AuxChannelLabel7;
extern lv_obj_t * ui_Container37;
extern lv_obj_t * ui_AuxChannelValue7;
extern lv_obj_t * ui_AuxChannelSymbol7;
extern lv_obj_t * ui_AuxChannelBar7;
extern lv_obj_t * ui_BackContainer8;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Container38;
extern lv_obj_t * ui_AuxChannelLabel8;
extern lv_obj_t * ui_Container39;
extern lv_obj_t * ui_AuxChannelValue8;
extern lv_obj_t * ui_AuxChannelSymbol8;
extern lv_obj_t * ui_AuxChannelBar8;
extern lv_obj_t * ui_BackContainer9;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Container40;
extern lv_obj_t * ui_AuxChannelLabel9;
extern lv_obj_t * ui_Container41;
extern lv_obj_t * ui_AuxChannelValue9;
extern lv_obj_t * ui_AuxChannelSymbol9;
extern lv_obj_t * ui_AuxChannelBar9;
extern lv_obj_t * ui_BackContainer10;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Container42;
extern lv_obj_t * ui_AuxChannelLabel10;
extern lv_obj_t * ui_Container43;
extern lv_obj_t * ui_AuxChannelValue10;
extern lv_obj_t * ui_AuxChannelSymbol10;
extern lv_obj_t * ui_AuxChannelBar10;
extern lv_obj_t * ui_BackContainer11;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Container44;
extern lv_obj_t * ui_AuxChannelLabel11;
extern lv_obj_t * ui_Container45;
extern lv_obj_t * ui_AuxChannelValue11;
extern lv_obj_t * ui_AuxChannelSymbol11;
extern lv_obj_t * ui_AuxChannelBar11;
extern lv_obj_t * ui_BackContainer12;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Container46;
extern lv_obj_t * ui_AuxChannelLabel12;
extern lv_obj_t * ui_Container47;
extern lv_obj_t * ui_AuxChannelValue12;
extern lv_obj_t * ui_AuxChannelSymbol12;
extern lv_obj_t * ui_AuxChannelBar12;
extern lv_obj_t * ui_BackContainer13;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_Container48;
extern lv_obj_t * ui_AuxChannelLabel13;
extern lv_obj_t * ui_Container49;
extern lv_obj_t * ui_AuxChannelValue13;
extern lv_obj_t * ui_AuxChannelSymbol13;
extern lv_obj_t * ui_AuxChannelBar13;
extern lv_obj_t * ui_BackContainer14;
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_Container50;
extern lv_obj_t * ui_AuxChannelLabel14;
extern lv_obj_t * ui_Container51;
extern lv_obj_t * ui_AuxChannelValue14;
extern lv_obj_t * ui_AuxChannelSymbol14;
extern lv_obj_t * ui_AuxChannelBar14;
extern lv_obj_t * ui_BackContainer15;
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_Container52;
extern lv_obj_t * ui_AuxChannelLabel15;
extern lv_obj_t * ui_Container53;
extern lv_obj_t * ui_AuxChannelValue15;
extern lv_obj_t * ui_AuxChannelSymbol15;
extern lv_obj_t * ui_AuxChannelBar15;
extern lv_obj_t * ui_BackContainer16;
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_Container54;
extern lv_obj_t * ui_AuxChannelLabel16;
extern lv_obj_t * ui_Container55;
extern lv_obj_t * ui_AuxChannelValue16;
extern lv_obj_t * ui_AuxChannelSymbol16;
extern lv_obj_t * ui_AuxChannelBar16;
extern lv_obj_t * ui_Container65;
extern lv_obj_t * ui_SettingsBtn3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

