// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_ANALOGCLUSTERSCREEN_H
#define UI_ANALOGCLUSTERSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_AnalogClusterScreen
extern void ui_AnalogClusterScreen_screen_init(void);
extern void ui_AnalogClusterScreen_screen_destroy(void);
extern lv_obj_t * ui_AnalogClusterScreen;
extern lv_obj_t * ui_Container11;
extern lv_obj_t * ui_LeftIndicator;
extern lv_obj_t * ui_Container13;
extern lv_obj_t * ui_HighBeam;
extern lv_obj_t * ui_LowBeam;
extern lv_obj_t * ui_Brake;
extern lv_obj_t * ui_Warning;
extern lv_obj_t * ui_RightIndicator;
extern lv_obj_t * ui_AnalogRPMSliderHorizontal;
extern lv_obj_t * ui_AnalogRPMSlider;
extern lv_obj_t * ui_SpeedAnalogGauge;
extern lv_obj_t * ui_SpeedGaugeIndicator;
extern lv_obj_t * ui_RPMGauge;
extern lv_obj_t * ui_RPMIndicator;
extern lv_obj_t * ui_Container12;
extern lv_obj_t * ui_AnalogGauge1;
extern lv_obj_t * ui_Container20;
extern lv_obj_t * ui_MidLevel;
extern lv_obj_t * ui_Image24;
extern lv_obj_t * ui_Container21;
extern lv_obj_t * ui_LowLevel1;
extern lv_obj_t * ui_HighLevel1;
extern lv_obj_t * ui_Container14;
extern lv_obj_t * ui_AnalogGaugeName1;
extern lv_obj_t * ui_AnalogGauge2;
extern lv_obj_t * ui_Container15;
extern lv_obj_t * ui_MidLevel1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Container22;
extern lv_obj_t * ui_LowLevel2;
extern lv_obj_t * ui_HighLevel2;
extern lv_obj_t * ui_Container23;
extern lv_obj_t * ui_AnalogGaugeName2;
extern lv_obj_t * ui_AnalogGauge3;
extern lv_obj_t * ui_Container24;
extern lv_obj_t * ui_MidLevel2;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Container25;
extern lv_obj_t * ui_LowLevel3;
extern lv_obj_t * ui_HighLevel3;
extern lv_obj_t * ui_Container26;
extern lv_obj_t * ui_AnalogGaugeName3;
extern lv_obj_t * ui_Container57;
extern lv_obj_t * ui_SettingsBtn2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

