// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

// COMPONENT ParaTile

lv_obj_t * ui_ParaTile_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_ParaTile;
    cui_ParaTile = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_ParaTile, 294);
    lv_obj_set_height(cui_ParaTile, 180);
    lv_obj_set_x(cui_ParaTile, 10);
    lv_obj_set_y(cui_ParaTile, 0);
    lv_obj_set_align(cui_ParaTile, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_ParaTile, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_ParaTile, lv_color_hex(0x1FF782), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_ParaTile, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_ParaTile, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_ParaTile, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Panel2;
    cui_Panel2 = lv_obj_create(cui_ParaTile);
    lv_obj_set_width(cui_Panel2, 286);
    lv_obj_set_height(cui_Panel2, 180);
    lv_obj_set_x(cui_Panel2, 5);
    lv_obj_set_y(cui_Panel2, 0);
    lv_obj_set_align(cui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Panel2, lv_color_hex(0x121317), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Container6;
    cui_Container6 = lv_obj_create(cui_Panel2);
    lv_obj_remove_style_all(cui_Container6);
    lv_obj_set_width(cui_Container6, 253);
    lv_obj_set_height(cui_Container6, 69);
    lv_obj_set_align(cui_Container6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_Container6, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_Container6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(cui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Name;
    cui_Name = lv_label_create(cui_Container6);
    lv_obj_set_width(cui_Name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Name, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Name, "C O O L A N T");
    lv_obj_set_style_text_color(cui_Name, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Name, &ui_font_SairaSemiCondensedRegualar16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Container7;
    cui_Container7 = lv_obj_create(cui_Container6);
    lv_obj_remove_style_all(cui_Container7);
    lv_obj_set_width(cui_Container7, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(cui_Container7, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(cui_Container7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_Container7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_Container7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(cui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Value;
    cui_Value = lv_label_create(cui_Container7);
    lv_obj_set_width(cui_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Value, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Value, "92");
    lv_obj_set_style_text_color(cui_Value, lv_color_hex(0x35D07A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Value, &ui_font_SairaSemiCondensedExtraBold56, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Symbol;
    cui_Symbol = lv_label_create(cui_Container7);
    lv_obj_set_width(cui_Symbol, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Symbol, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Symbol, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Symbol, "°C");
    lv_obj_set_style_text_color(cui_Symbol, lv_color_hex(0x6B7178), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Symbol, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Symbol, &ui_font_SairaSemiCondensedExtraBold24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_Symbol, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_Symbol, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_Symbol, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_Symbol, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_PARATILE_NUM);
    children[UI_COMP_PARATILE_PARATILE] = cui_ParaTile;
    children[UI_COMP_PARATILE_PANEL2] = cui_Panel2;
    children[UI_COMP_PARATILE_PANEL2_CONTAINER6] = cui_Container6;
    children[UI_COMP_PARATILE_PANEL2_CONTAINER6_NAME] = cui_Name;
    children[UI_COMP_PARATILE_PANEL2_CONTAINER6_CONTAINER7] = cui_Container7;
    children[UI_COMP_PARATILE_PANEL2_CONTAINER6_CONTAINER7_VALUE] = cui_Value;
    children[UI_COMP_PARATILE_PANEL2_CONTAINER6_CONTAINER7_SYMBOL] = cui_Symbol;
    lv_obj_add_event_cb(cui_ParaTile, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_ParaTile, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_ParaTile_create_hook(cui_ParaTile);
    return cui_ParaTile;
}

