// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_PARATILE_H
#define _UI_COMP_PARATILE_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT ParaTile
#define UI_COMP_PARATILE_PARATILE 0
#define UI_COMP_PARATILE_PANEL2 1
#define UI_COMP_PARATILE_PANEL2_CONTAINER6 2
#define UI_COMP_PARATILE_PANEL2_CONTAINER6_NAME 3
#define UI_COMP_PARATILE_PANEL2_CONTAINER6_CONTAINER7 4
#define UI_COMP_PARATILE_PANEL2_CONTAINER6_CONTAINER7_VALUE 5
#define UI_COMP_PARATILE_PANEL2_CONTAINER6_CONTAINER7_SYMBOL 6
#define _UI_COMP_PARATILE_NUM 7
lv_obj_t *ui_ParaTile_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
