// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_MAINSCREEN
#define UI_MAINSCREEN

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainScreen
extern void ui_MainScreen_screen_init(void);
extern void ui_MainScreen_screen_destroy(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_RPMSlider;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_DigitalChannel1;
extern lv_obj_t * ui_DigitalChannel2;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_GearShiftValue;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_SpeedLabel;
extern lv_obj_t * ui_SpeedValue;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_LambdaValue;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_DigitalChannel3;
extern lv_obj_t * ui_DigitalChannel4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif /* UI_MAINSCREEN */

