// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SETTINGSSCREEN_H
#define UI_SETTINGSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SettingsScreen
extern void ui_SettingsScreen_screen_init(void);
extern void ui_SettingsScreen_screen_destroy(void);
extern lv_obj_t * ui_SettingsScreen;
extern lv_obj_t * ui_RaceMainBtn;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_AnalogClusterBtn;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_FullDataBtn;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_WarningBtn;
extern lv_obj_t * ui_Label9;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

