// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_SplashScreen = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_LoadingSlider = NULL;
// event funtions

// build funtions

void ui_SplashScreen_screen_init(void)
{
    ui_SplashScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SplashScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SplashScreen, lv_color_hex(0x141519), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SplashScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_SplashScreen);
    lv_img_set_src(ui_Image1, &ui_img_background_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LoadingSlider = lv_slider_create(ui_SplashScreen);
    lv_slider_set_value(ui_LoadingSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_LoadingSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_LoadingSlider, 0,
                                                                                                  LV_ANIM_OFF);
    lv_obj_set_width(ui_LoadingSlider, 420);
    lv_obj_set_height(ui_LoadingSlider, 6);
    lv_obj_set_x(ui_LoadingSlider, -19);
    lv_obj_set_y(ui_LoadingSlider, 105);
    lv_obj_set_align(ui_LoadingSlider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_LoadingSlider, lv_color_hex(0xFF5A4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LoadingSlider, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_LoadingSlider, lv_color_hex(0xE11D2A), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LoadingSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_LoadingSlider, lv_color_hex(0xFF5A4D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_LoadingSlider, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_LoadingSlider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LoadingSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

}

void ui_SplashScreen_screen_destroy(void)
{
    if(ui_SplashScreen) lv_obj_del(ui_SplashScreen);

    // NULL screen variables
    ui_SplashScreen = NULL;
    ui_Image1 = NULL;
    ui_LoadingSlider = NULL;

}
