// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_SettingsScreen = NULL;
lv_obj_t * ui_RaceMainBtn = NULL;
lv_obj_t * ui_Label24 = NULL;
lv_obj_t * ui_AnalogClusterBtn = NULL;
lv_obj_t * ui_Label34 = NULL;
lv_obj_t * ui_FullDataBtn = NULL;
lv_obj_t * ui_Label35 = NULL;
lv_obj_t * ui_WarningBtn = NULL;
lv_obj_t * ui_Label9 = NULL;
// event funtions

// build funtions

void ui_SettingsScreen_screen_init(void)
{
    ui_SettingsScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SettingsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RaceMainBtn = lv_btn_create(ui_SettingsScreen);
    lv_obj_set_width(ui_RaceMainBtn, 116);
    lv_obj_set_height(ui_RaceMainBtn, 50);
    lv_obj_set_x(ui_RaceMainBtn, -152);
    lv_obj_set_y(ui_RaceMainBtn, 20);
    lv_obj_set_align(ui_RaceMainBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RaceMainBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RaceMainBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label24 = lv_label_create(ui_RaceMainBtn);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "RACE/MAIN");

    ui_AnalogClusterBtn = lv_btn_create(ui_SettingsScreen);
    lv_obj_set_width(ui_AnalogClusterBtn, 199);
    lv_obj_set_height(ui_AnalogClusterBtn, 50);
    lv_obj_set_x(ui_AnalogClusterBtn, 70);
    lv_obj_set_y(ui_AnalogClusterBtn, 21);
    lv_obj_set_align(ui_AnalogClusterBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AnalogClusterBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_AnalogClusterBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label34 = lv_label_create(ui_AnalogClusterBtn);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "ANALOG CLUSTER");

    ui_FullDataBtn = lv_btn_create(ui_SettingsScreen);
    lv_obj_set_width(ui_FullDataBtn, 183);
    lv_obj_set_height(ui_FullDataBtn, 50);
    lv_obj_set_x(ui_FullDataBtn, 306);
    lv_obj_set_y(ui_FullDataBtn, 17);
    lv_obj_set_align(ui_FullDataBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FullDataBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_FullDataBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label35 = lv_label_create(ui_FullDataBtn);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "FULL DATA GRID");

    ui_WarningBtn = lv_btn_create(ui_SettingsScreen);
    lv_obj_set_width(ui_WarningBtn, 183);
    lv_obj_set_height(ui_WarningBtn, 50);
    lv_obj_set_x(ui_WarningBtn, 76);
    lv_obj_set_y(ui_WarningBtn, 126);
    lv_obj_set_align(ui_WarningBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WarningBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WarningBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label9 = lv_label_create(ui_WarningBtn);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Warning");

}

void ui_SettingsScreen_screen_destroy(void)
{
    if(ui_SettingsScreen) lv_obj_del(ui_SettingsScreen);

    // NULL screen variables
    ui_SettingsScreen = NULL;
    ui_RaceMainBtn = NULL;
    ui_Label24 = NULL;
    ui_AnalogClusterBtn = NULL;
    ui_Label34 = NULL;
    ui_FullDataBtn = NULL;
    ui_Label35 = NULL;
    ui_WarningBtn = NULL;
    ui_Label9 = NULL;

}
