// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_WarningScreen = NULL;
lv_obj_t * ui_Container76 = NULL;
lv_obj_t * ui_Image17 = NULL;
lv_obj_t * ui_Label21 = NULL;
lv_obj_t * ui_WarningsLabel = NULL;
lv_obj_t * ui_Container74 = NULL;
lv_obj_t * ui_BackWarnContainer = NULL;
lv_obj_t * ui_Panel27 = NULL;
lv_obj_t * ui_Container73 = NULL;
lv_obj_t * ui_Container77 = NULL;
lv_obj_t * ui_WarningChannel = NULL;
lv_obj_t * ui_WarningDetailLabel = NULL;
lv_obj_t * ui_Container78 = NULL;
lv_obj_t * ui_ChannelValue = NULL;
lv_obj_t * ui_WarningRange = NULL;
lv_obj_t * ui_WarningDot = NULL;
// event funtions

// build funtions

void ui_WarningScreen_screen_init(void)
{
    ui_WarningScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WarningScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_WarningScreen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_WarningScreen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_WarningScreen, lv_color_hex(0x1C1E22), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WarningScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container76 = lv_obj_create(ui_WarningScreen);
    lv_obj_remove_style_all(ui_Container76);
    lv_obj_set_width(ui_Container76, 1024);
    lv_obj_set_height(ui_Container76, 100);
    lv_obj_set_align(ui_Container76, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container76, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container76, lv_color_hex(0x2A0D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container76, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image17 = lv_img_create(ui_Container76);
    lv_img_set_src(ui_Image17, &ui_img_mark_png);
    lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image17, -458);
    lv_obj_set_y(ui_Image17, -1);
    lv_obj_set_align(ui_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label21 = lv_label_create(ui_Container76);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, -272);
    lv_obj_set_y(ui_Label21, -6);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "ENGINE WARNINGS");
    lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label21, &ui_font_SairaSemiCondensedExtraBold40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WarningsLabel = lv_label_create(ui_Container76);
    lv_obj_set_width(ui_WarningsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WarningsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WarningsLabel, -279);
    lv_obj_set_y(ui_WarningsLabel, 23);
    lv_obj_set_align(ui_WarningsLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WarningsLabel, "2 ACTIVE · 2 CAUTION · REDUCE LOAD");
    lv_obj_set_style_text_color(ui_WarningsLabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WarningsLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WarningsLabel, &ui_font_SairaSemiCondensedRegualar16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container74 = lv_obj_create(ui_WarningScreen);
    lv_obj_remove_style_all(ui_Container74);
    lv_obj_set_width(ui_Container74, 1024);
    lv_obj_set_height(ui_Container74, 453);
    lv_obj_set_align(ui_Container74, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container74, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container74, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container74, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container74, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container74, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container74, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container74, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container74, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container74, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackWarnContainer = lv_obj_create(ui_Container74);
    lv_obj_set_width(ui_BackWarnContainer, 987);
    lv_obj_set_height(ui_BackWarnContainer, 78);
    lv_obj_set_x(ui_BackWarnContainer, -5);
    lv_obj_set_y(ui_BackWarnContainer, -252);
    lv_obj_set_align(ui_BackWarnContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BackWarnContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BackWarnContainer, lv_color_hex(0xF5A623), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackWarnContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BackWarnContainer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BackWarnContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel27 = lv_obj_create(ui_BackWarnContainer);
    lv_obj_set_width(ui_Panel27, 980);
    lv_obj_set_height(ui_Panel27, 78);
    lv_obj_set_x(ui_Panel27, 5);
    lv_obj_set_y(ui_Panel27, 0);
    lv_obj_set_align(ui_Panel27, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel27, lv_color_hex(0x121317), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel27, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel27, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container73 = lv_obj_create(ui_Panel27);
    lv_obj_remove_style_all(ui_Container73);
    lv_obj_set_width(ui_Container73, 909);
    lv_obj_set_height(ui_Container73, 64);
    lv_obj_set_x(ui_Container73, 7);
    lv_obj_set_y(ui_Container73, 2);
    lv_obj_set_align(ui_Container73, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container73, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container73, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container73, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container77 = lv_obj_create(ui_Container73);
    lv_obj_remove_style_all(ui_Container77);
    lv_obj_set_width(ui_Container77, 163);
    lv_obj_set_height(ui_Container77, 50);
    lv_obj_set_align(ui_Container77, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container77, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container77, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container77, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WarningChannel = lv_label_create(ui_Container77);
    lv_obj_set_width(ui_WarningChannel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WarningChannel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WarningChannel, -3);
    lv_obj_set_y(ui_WarningChannel, 1);
    lv_obj_set_align(ui_WarningChannel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WarningChannel, "C O O L A N T");
    lv_obj_set_style_text_color(ui_WarningChannel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WarningChannel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WarningChannel, &ui_font_SairaSemiCondensedExtraBold24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_WarningChannel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_WarningChannel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_WarningChannel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_WarningChannel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WarningDetailLabel = lv_label_create(ui_Container77);
    lv_obj_set_width(ui_WarningDetailLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WarningDetailLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WarningDetailLabel, 0);
    lv_obj_set_y(ui_WarningDetailLabel, 13);
    lv_obj_set_align(ui_WarningDetailLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WarningDetailLabel, "APPROACHING LIMIT");
    lv_obj_set_style_text_color(ui_WarningDetailLabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WarningDetailLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WarningDetailLabel, &ui_font_SairaSemiCondensedRegualar16,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container78 = lv_obj_create(ui_Container73);
    lv_obj_remove_style_all(ui_Container78);
    lv_obj_set_width(ui_Container78, 224);
    lv_obj_set_height(ui_Container78, 67);
    lv_obj_set_x(ui_Container78, 17);
    lv_obj_set_y(ui_Container78, -36);
    lv_obj_set_align(ui_Container78, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container78, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container78, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_END);
    lv_obj_clear_flag(ui_Container78, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ChannelValue = lv_label_create(ui_Container78);
    lv_obj_set_width(ui_ChannelValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ChannelValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChannelValue, -3);
    lv_obj_set_y(ui_ChannelValue, 1);
    lv_obj_set_align(ui_ChannelValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ChannelValue, "0.98");
    lv_obj_set_style_text_color(ui_ChannelValue, lv_color_hex(0xF5A623), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ChannelValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ChannelValue, &ui_font_SairaSemiCondensedExtraBold40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WarningRange = lv_label_create(ui_Container78);
    lv_obj_set_width(ui_WarningRange, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WarningRange, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WarningRange, 0);
    lv_obj_set_y(ui_WarningRange, 13);
    lv_obj_set_align(ui_WarningRange, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WarningRange, "0-1.3 LA");
    lv_obj_set_style_text_color(ui_WarningRange, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WarningRange, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WarningRange, &ui_font_SairaSemiCondensedRegualar16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WarningDot = lv_obj_create(ui_BackWarnContainer);
    lv_obj_remove_style_all(ui_WarningDot);
    lv_obj_set_width(ui_WarningDot, 17);
    lv_obj_set_height(ui_WarningDot, 17);
    lv_obj_set_x(ui_WarningDot, -465);
    lv_obj_set_y(ui_WarningDot, -1);
    lv_obj_set_align(ui_WarningDot, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WarningDot, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WarningDot, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WarningDot, lv_color_hex(0xF5A623), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WarningDot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_WarningScreen_screen_destroy(void)
{
    if(ui_WarningScreen) lv_obj_del(ui_WarningScreen);

    // NULL screen variables
    ui_WarningScreen = NULL;
    ui_Container76 = NULL;
    ui_Image17 = NULL;
    ui_Label21 = NULL;
    ui_WarningsLabel = NULL;
    ui_Container74 = NULL;
    ui_BackWarnContainer = NULL;
    ui_Panel27 = NULL;
    ui_Container73 = NULL;
    ui_Container77 = NULL;
    ui_WarningChannel = NULL;
    ui_WarningDetailLabel = NULL;
    ui_Container78 = NULL;
    ui_ChannelValue = NULL;
    ui_WarningRange = NULL;
    ui_WarningDot = NULL;

}
