// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_WARNINGSCREEN_H
#define UI_WARNINGSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WarningScreen
extern void ui_WarningScreen_screen_init(void);
extern void ui_WarningScreen_screen_destroy(void);
extern lv_obj_t * ui_WarningScreen;
extern lv_obj_t * ui_Container76;
extern lv_obj_t * ui_Image17;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_WarningsLabel;
extern lv_obj_t * ui_Container74;
extern lv_obj_t * ui_BackWarnContainer;
extern lv_obj_t * ui_Panel27;
extern lv_obj_t * ui_Container73;
extern lv_obj_t * ui_Container77;
extern lv_obj_t * ui_WarningChannel;
extern lv_obj_t * ui_WarningDetailLabel;
extern lv_obj_t * ui_Container78;
extern lv_obj_t * ui_ChannelValue;
extern lv_obj_t * ui_WarningRange;
extern lv_obj_t * ui_WarningDot;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

